# Generated by Django 2.2.7 on 2019-12-11 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TestModel', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tnum', models.CharField(max_length=20)),
                ('tjob', models.CharField(max_length=20)),
                ('tgit', models.CharField(max_length=20)),
            ],
        ),
    ]
