# Generated by Django 2.2.7 on 2019-12-16 05:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TestModel', '0003_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='note',
            field=models.CharField(default=1, max_length=32),
            preserve_default=False,
        ),
    ]
