# Generated by Django 2.2.7 on 2019-12-17 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TestModel', '0004_user_note'),
    ]

    operations = [
        migrations.CreateModel(
            name='Democtl',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('demoname', models.CharField(max_length=32)),
                ('demoattr', models.CharField(max_length=16)),
                ('democmdname', models.CharField(max_length=32)),
            ],
        ),
    ]
