# Generated by Django 2.2.7 on 2019-12-24 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TestModel', '0006_auto_20191217_1441'),
    ]

    operations = [
        migrations.CreateModel(
            name='Demostate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('demoname', models.CharField(max_length=32)),
                ('demoattr', models.CharField(max_length=16)),
                ('demohost', models.CharField(max_length=32)),
                ('demoport', models.CharField(max_length=32)),
                ('demostate', models.CharField(max_length=16)),
            ],
        ),
    ]
